# fly.toml app configuration file generated for demo-phonebook-deploy-practice on 2023-08-22T12:55:21-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "demo-phonebook-deploy-practice"
primary_region = "bos"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
