

###

DELETE http://localhost:3001/api/persons/9



### 

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Sobaka Sobaka",
    "number": "999-99-99"
  }

###

GET http://localhost:3001/api/persons
content-type: application/json



